info:
  description: CAS Configuration

cas:
  authn:
    accept:
      enabled: false
    ldap[0]:
      bind-dn: cn=admin,dc=example,dc=org
      bind-credential: admin
      base-dn: dc=example,dc=org
      search-filter: cn={user}
      password-encoder:
        type: NONE
      ldap-url: ldap://openldap:389
      use-start-tls: false
      type: AUTHENTICATED

    attribute-repository:
      core:
        default-attributes-to-release: sn
      ldap[0]:
        id: ldapRepository
        order: 0
        subtree-search: true
        base-dn: dc=example,dc=org
        bind-dn: cn=admin,dc=example,dc=org
        bind-credential: admin
        ldap-url: ldap://openldap:389
        search-filter: cn={user}
        use-start-tls: false
        attributes:
          sn: lastName
          givenName: firstName

      attribute-definition-store:
        json:
          location: file:/etc/cas/config/test.json

  person-directory:
    attribute-resolution-enabled: true
    active-attribute-repository-ids: ldapRepository
    principal-attribute: cn

