- name: Disable SELinux policy permanently
  ansible.posix.selinux:
    policy: targeted
    state: disabled

- name: Disable SELinux policy
  shell:
    cmd: setenforce 0

- name: Gather firewalld is installed
  package_facts:
    manager: auto

- name: Stop and disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: "'firewalld' in ansible_facts.packages"

- name: Enable epel-release
  dnf:
    name: epel
    state: present

- name: Install necessary packages
  dnf:
    name:
      - wget
      - bind-utils
      - vim
      - nload
    state: present
    update_cache: true

