- name: Enable network service
  systemd:
    name: network
    enabled: true

- name: Copy ifcfg-lo-pdns-int to /etc/sysconfig/network-scripts/
  copy:
    src: ifcfg-lo-pdns-int
    dest: /etc/sysconfig/network-scripts/ifcfg-lo-pdns-int
    owner: root
    group: root

- name: Copy ifcfg-lo-pdns-pub to /etc/sysconfig/network-scripts/
  copy:
    src: ifcfg-lo-pdns-pub
    dest: /etc/sysconfig/network-scripts/ifcfg-lo-pdns-pub
    owner: root
    group: root

- name: Copy ifcfg-lo-pdns-rec-int to /etc/sysconfig/network-scripts/
  copy:
    src: ifcfg-lo-pdns-rec-int
    dest: /etc/sysconfig/network-scripts/ifcfg-lo-pdns-rec-int
    owner: root
    group: root

- name: Copy ifcfg-lo-bind-int to /etc/sysconfig/network-scripts/
  copy:
    src: ifcfg-lo-bind-int
    dest: /etc/sysconfig/network-scripts/ifcfg-lo-bind-int
    owner: root
    group: root

