# General
install_ansible_modules: "true"
disable_transparent_huge_pages: "true"
setup_interface: "false"

#DIM-Network
network_scripts_url: "https://dl.rockylinux.org/pub/rocky/9/devel/x86_64/os/Packages/n/network-scripts-10.11.5-1.el9.x86_64.rpm"
network_scripts_dest: "/tmp"
network_scripts_package: "network-scripts-10.11.5-1.el9.x86_64.rpm"

# DIM DB
dim_db_name: "dim"
pdns_int_db_name: "pdns_int"
pdns_pub_db_name: "pdns_pub"

# DIM DB info
dim_db_user_name: "dim_user"
dim_db_user_password: "dim_pass"
dim_db_priv: "dim.*:ALL"

# pdns_int DB info
dim_pdns_int_db_user_name: "dim_pdns_int_user"
dim_pdns_int_db_user_password: "SuperSecret1"
dim_pdns_int_db_priv: "pdns_int.*:INSERT,UPDATE,DELETE,SELECT"
pdns_int_db_user_name: "pdns_int_user"
pdns_int_db_user_password: "SuperSecret4"
pdns_int_db_priv: "pdns_int.*:SELECT"

# pdns_pub DB info
dim_pdns_pub_db_user_name: "dim_pdns_pub_user"
dim_pdns_pub_db_user_password: "SuperSecret2"
dim_pdns_pub_db_priv: "pdns_pub.*:INSERT,UPDATE,DELETE,SELECT"
pdns_pub_db_user_name: "pdns_pub_user"
pdns_pub_db_user_password: "SuperSecret3"
pdns_pub_db_priv: "pdns_pub.*:SELECT"

# SQL
sql_url: "https://raw.githubusercontent.com/1and1/dim/master/dim/pdns.sql"
sql_file_path: "/tmp/pdns.sql"

# PowerDNS
pdns_conf_dir: "/etc/pdns"
pdns_recursor_conf_path: "/etc/pdns-recursor"
