name: Build PDNS-Output

on:
  push:
    tags:
      - 'pdns-output-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Build pdns-output
      run: gradle shadowJar
      working-directory: pdns-output
      
    - uses: actions/upload-artifact@v2
      with:
        name: pdns-output
        path: pdns-output/pdns-output/build/libs/pdns-output*-all.jar
