name: Build PDNS-Output

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 12, 13, 14, 15 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Build jdnssec-dnsjava
      run: gradle build -x test && gralde publishToMavenLocal
      working-directory: jdnssec-dnsjava
    - name: Build jdnssec-tools
      run: gradle build -x test && gralde publishToMavenLocal
      working-directory: jdnssec-tools
    - name: Build gmp-rsa
      run: gradle build -x test && gralde publishToMavenLocal
      working-directory: gmp-rsa
      
#    - uses: actions/upload-artifact@v2
#      with:
#        name: artifact-jdk-${{ matrix.java }}
#        path: target/checkmk-api-client*jar
